export const Token = {
  APP: "APP",
  REQUEST_HANDLER: "REQUEST_HANDLER",
  TMDB: "TMDB",
  TVMAZE: "TVMAZE",
  DONTORRENT_SCRAPPER: "DONTORRENT_SCRAPPER",
  DONTORRENT_WRAPPER: "DONTORRENT_WRAPPER",
  DONTORRENT_TV_ADAPTER: "DONTORRENT_TV_ADAPTER",
  MARCIANOTORENT_SCRAPPER: "MARCIANOTORENT_SCRAPPER",
  MARCIANOTORENT_WRAPPER: "MARCIANOTORENT_WRAPPER",
  MOVIE_ADAPTER: "MOVIE_ADAPTER",
  LOGGER: "LOGGER",
} as const;

export type Token = (typeof Token)[keyof typeof Token];
