export const Token = {
  APP: "APP",
  REQUEST_HANDLER: "REQUEST_HANDLER",
  TMDB: "TMDB",
  TVMAZE: "TVMAZE",
  DONTORRENT_SCRAPPER: "DONTORRENT_SCRAPPER",
  DONTORRENT_WRAPPER: "DONTORRENT_WRAPPER",
  MARCIANOTORENT_SCRAPPER: "MARCIANOTORENT_SCRAPPER",
  MARCIANOTORENT_WRAPPER: "MARCIANOTORENT_WRAPPER",
  WOLFMAX4K_SCRAPPER: "WOLFMAX4K_SCRAPPER",
  WOLFMAX4K_WRAPPER: "WOLFMAX4K_WRAPPER",
  MOVIE_ADAPTER: "MOVIE_ADAPTER",
  TV_ADAPTER: "TV_ADAPTER",
  LOGGER: "LOGGER",
} as const;

export type Token = (typeof Token)[keyof typeof Token];
