export const TorznabErrorCode = {
  // Authentication & Account (100-107)
  INCORRECT_USER_CREDENTIALS: 100,
  ACCOUNT_SUSPENDED: 101,
  INSUFFICIENT_PRIVILEGES: 102,
  REGISTRATION_DENIED: 103,
  REGISTRATIONS_CLOSED: 104,
  INVALID_REGISTRATION_EMAIL_TAKEN: 105,
  INVALID_REGISTRATION_BAD_FORMAT: 106,
  REGISTRATION_FAILED_DATA_ERROR: 107,

  // Request Errors (200-203)
  MISSING_PARAMETER: 200,
  INCORRECT_PARAMETER: 201,
  NO_SUCH_FUNCTION: 202,
  FUNCTION_NOT_AVAILABLE: 203,

  // Item Errors (300-301)
  NO_SUCH_ITEM: 300,
  ITEM_ALREADY_EXISTS: 301,

  // System Errors (900-910)
  UNKNOWN_ERROR: 900,
  API_DISABLED: 910,
} as const;

export type TorznabErrorCodeValue =
  (typeof TorznabErrorCode)[keyof typeof TorznabErrorCode];
